### ISSUE TITLE
Help with uploaded data

### ISSUE THREAD

**Issue by mihinduk** [HandleyLab/Bioinformatics-SOPs#2]
Hi Guys,

I have uploaded a data file (data.txt) BUT it just displays when you click the link (not as a csv).  I would like to host the file and allow people to download the csv so that they can try things for themselves but haven't figured out how to do that (if possible).  HELP!

**Comment by shandley** [comment]
There is no data.txt file in the GitHub repo.

**Comment by mihinduk** [comment]
If you go to the dplyr page and click on the data link, it takes you to the data - but not the way I want.

**Comment by shandley** [comment]
then the only thing you can do is tell them to right click on it to download
