### ISSUE TITLE
Andrew's flowchart

### ISSUE THREAD

**Issue by mihinduk** [HandleyLab/Bioinformatics-SOPs#3]
[Handley_lab_stats_decision_tree_final.pdf](https://github.com/HandleyLab/Bioinformatics-SOPs/files/6917866/Handley_lab_stats_decision_tree_final.pdf)

**Comment by shandley** [comment]
Since part of the lab wiki is designed to teach people how to use GitHub can we please add this using the traditional clone / pull request method instead?

If you add this as a file to the repo (not the wiki) you can create a link to it from the wiki.
